=== build-one-labs/starter/.deploy/deployment.config.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "globals": {
      "type": "object",
      "properties": {
        "dataImage": {
          "type": "string"
        },
        "appServerTsImage": {
          "type": "string"
        },
        "webAppImage": {
          "type": "string"
        }
      },
      "patternProperties": {
        "^.*$": {
          "type": "string"
        }
      }
    },
    "networks": {
      "anyOf": [
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        {
          "type": "object",
          "patternProperties": {
            "^.*$": {
              "anyOf": [
                {
                  "type": "null"
                },
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "driver": {
                      "type": "string"
                    },
                    "driver_opts": {
                      "type": "object"
                    },
                    "external": {
                      "type": "boolean"
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "volumes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "services": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "image": {
              "type": "string"
            },
            "build": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "context": {
                  "type": "string"
                },
                "dockerfile": {
                  "type": "string"
                }
              }
            },
            "init": {
              "type": "boolean"
            },
            "working_dir": {
              "type": "string"
            },
            "restart": {
              "type": "string",
              "enum": [
                "no",
                "always",
                "unless-stopped"
              ]
            },
            "healthcheck": {
              "type": "object",
              "properties": {
                "test": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            },
            "scale": {
              "type": "string"
            },
            "ports": {
              "type": "object",
              "patternProperties": {
                "^.*$": {
                  "type": "string"
                }
              }
            },
            "ulimits": {
              "type": "object",
              "properties": {
                "nofile": {
                  "type": "object",
                  "properties": {
                    "soft": {
                      "type": "number"
                    },
                    "hard": {
                      "type": "number"
                    }
                  }
                }
              }
            },
            "deploy": {
              "type": "object",
              "resources": {
                "type": "object",
                "limits": {
                  "type": "object",
                  "cpus": {
                    "type": "string"
                  },
                  "memory": {
                    "type": "string"
                  }
                },
                "reservations": {
                  "type": "object",
                  "cpus": {
                    "type": "string"
                  },
                  "memory": {
                    "type": "string"
                  }
                }
              }
            },
            "environment": {
              "type": "object",
              "additionalProperties": false,
              "patternProperties": {
                "^.*$": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  ]
                }
              }
            },
            "labels": {
              "type": "object",
              "additionalProperties": false,
              "patternProperties": {
                "^.*$": {
                  "anyOf": [
                    {
                      "type": "string"
                    }
                  ]
                }
              }
            },
            "volumes": {
              "type": "object",
              "additionalProperties": false,
              "patternProperties": {
                "^.*$": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "type": "string"
                    }
                  ]
                }
              }
            },
            "depends_on": {
              "anyOf": [
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                {
                  "type": "object",
                  "patternProperties": {
                    "^.*$": {
                      "additionalProperties": false,
                      "properties": {
                        "condition": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              ]
            },
            "networks": {
              "anyOf": [
                {
                  "type": "object",
                  "patternProperties": {
                    "^.*$": {
                      "type": "null"
                    }
                  }
                },
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              ]
            },
            "command": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              ]
            },
            "entrypoint": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              ]
            },
            "stop_grace_period": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== build-one-labs/starter/.deploy/workspace.deployment.config.json
{
  "$schema": "deployment.config.schema.json",
  "globals": {
    "appUrl": "${APP_URL:-}",
    "authenticationTrustedOrigins": "${APP_URL},http://localhost:8080,https://localhost:8080",
    "authenticationUrl": "${AUTH_URL:-http://auth_server:3000}",
    "automationHubImage": "docker.cloudsmith.io/buildone/repository/automation-hub-1-121-2-1:1.12.6",
    "automationHubDBImage": "docker.cloudsmith.io/buildone/repository/automation-hub-db:1.12.6",
    "postgresDbImage": "docker.cloudsmith.io/buildone/repository/build-one-postgres-db:17-2",
    "caddyImage": "docker.cloudsmith.io/buildone/repository/buildone-caddy:24.3.0-VG.103",
    "swatAppServerTsImage": "docker.cloudsmith.io/buildone/repository/buildone-swat-app-server-ts:24.3.0-VG.103",
    "appServerTsImage": "docker.cloudsmith.io/buildone/repository/buildone-app-server-ts:24.3.0-VG.103",
    "webAppImage": "docker.cloudsmith.io/buildone/repository/buildone-web-app:24.3.0-VG.103"
  },
  "volumes": [
    "ah_db_storage",
    "app_db_storage",
    "auth_db_storage",
    "b1_db_storage",
    "swat_app_uploads"
  ],
  "networks": [
    "app-network"
  ],
  "services": {
    "caddy": {
      "image": "#globals.caddyImage",
      "restart": "unless-stopped",
      "networks": [
        "app-network"
      ],
      "command": [
        "caddy",
        "run",
        "--config",
        "/etc/caddy/Caddyfile",
        "--adapter",
        "caddyfile"
      ],
      "ports": {
        "8080": "8080"
      }
    },
    "b1_db_server": {
      "image": "#globals.postgresDbImage",
      "restart": "unless-stopped",
      "environment": {
        "RESET_DATABASES": "${RESET_DATABASES:-FALSE}"
      },
      "healthcheck": {
        "test": [
          "CMD-SHELL",
          "/wait_for_db.sh"
        ],
        "interval": "5s",
        "timeout": "5s",
        "retries": 10
      },
      "networks": [
        "app-network"
      ],
      "volumes": {
        "/var/lib/postgresql/data": "b1_db_storage"
      },
      "ports": {
        "5432": "5432"
      }
    },
    "swat_app_server_ts": {
      "image": "#globals.swatAppServerTsImage",
      "restart": "unless-stopped",
      "environment": {
        "APP_URL": "#globals.appUrl",
        "BETTER_AUTH_SECRET": "${BETTER_AUTH_SECRET}",
        "GOOGLE_API_KEY": "${GOOGLE_API_KEY:-}",
        "B1_OPEN_EDGE_PASOE_URL": "${B1_OPEN_EDGE_PASOE_URL:-}",
        "IMPORT_DATA": "false",
        "PORT": "3000",
        "UPLOAD_DIR": "/app-data/uploads",
        "B1_DATA_FOLDER": "/data/b1",
        "APP_DATA_FOLDER": "/data/app",
        "B1_DATABASE_URL": "${B1_DATABASE_URL:-postgres://${B1_DATABASE_CREDENTIALS:-${DEFAULT_DATABASE_CREDENTIALS}}@b1_db_server:5432/b1?sslmode=disable}",
        "AUTH_URL": "#globals.authenticationUrl",
        "B1_FRAMEWORK_DEVELOPMENT": "false",
        "OPENAI_API_KEY": "${OPENAI_API_KEY:-}"
      },
      "networks": [
        "app-network"
      ],
      "volumes": {
        "/app-data": "${WORKSPACE_ROOT}/data",
        "/data/b1": "${WORKSPACE_ROOT}/node_modules/@buildone/swat-data",
        "/data/app": "${WORKSPACE_ROOT}/src/data"
      },
      "depends_on": {
        "b1_db_server": {
          "condition": "service_healthy"
        }
      },
      "init": true,
      "ports": {
        "3000": "3000"
      }
    },
    "app_db_server": {
      "image": "#globals.postgresDbImage",
      "restart": "unless-stopped",
      "environment": {
        "POSTGRES_DB": "app_db",
        "RESET_DATABASES": "${RESET_DATABASES:-FALSE}"
      },
      "healthcheck": {
        "test": [
          "CMD-SHELL",
          "/wait_for_db.sh"
        ],
        "interval": "5s",
        "timeout": "5s",
        "retries": 10
      },
      "networks": [
        "app-network"
      ],
      "volumes": {
        "/var/lib/postgresql/data": "app_db_storage"
      },
      "ports": {
        "5432": "15432"
      }
    },
    "app_server_ts": {
      "image": "nomad123/codespaces-nestjs-development:slim",
      "restart": "unless-stopped",
      "environment": {
        "PORT": "3000",
        "APP_DATABASE_URL": "${APP_DATABASE_URL:-postgres://${APP_DATABASE_CREDENTIALS:-${DEFAULT_DATABASE_CREDENTIALS}}@app_db_server:5432/app_db?sslmode=disable}",
        "AUTH_URL": "#globals.authenticationUrl",
        "BETTER_AUTH_SECRET": "${BETTER_AUTH_SECRET}",
        "NODE_ENV": "development"
      },
      "networks": [
        "app-network"
      ],
      "depends_on": {
        "app_db_server": {
          "condition": "service_healthy"
        }
      },
      "init": true,
      "ports": {
        "3000": "3001",
        "9229": "3011"
      },
      "working_dir": "/workspace/src/app-server-ts",
      "command": "./start.sh",
      "volumes": {
        "/workspace": "${WORKSPACE_ROOT}"
      }
    },
    "n8n_db_server": {
      "image": "#globals.automationHubDBImage",
      "restart": "unless-stopped",
      "healthcheck": {
        "test": [
          "CMD-SHELL",
          "/wait_for_db.sh"
        ],
        "interval": "5s",
        "timeout": "5s",
        "retries": 10
      },
      "networks": [
        "app-network"
      ],
      "volumes": {
        "/var/lib/postgresql/data": "ah_db_storage"
      }
    },
    "n8n": {
      "image": "#globals.automationHubImage",
      "restart": "unless-stopped",
      "environment": {
        "AUTHENTICATION_URI": "#globals.authenticationUrl",
        "DB_POSTGRESDB_HOST": "n8n_db_server",
        "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS": "false",
        "N8N_SECURE_COOKIE": "false",
        "WEBHOOK_URL": "${N8N_URL}",
        "B1_N8N_ENV": "devel"
      },
      "networks": [
        "app-network"
      ],
      "depends_on": {
        "n8n_db_server": {
          "condition": "service_healthy"
        }
      },
      "ports": {
        "5678": "5678"
      },
      "volumes": {
        "/workspace": "${WORKSPACE_ROOT}"
      }
    },
    "auth_db_server": {
      "image": "#globals.postgresDbImage",
      "restart": "unless-stopped",
      "environment": {
        "POSTGRES_DB": "auth_db",
        "RESET_DATABASES": "${RESET_DATABASES:-FALSE}"
      },
      "healthcheck": {
        "test": [
          "CMD-SHELL",
          "/wait_for_db.sh"
        ],
        "interval": "5s",
        "timeout": "5s",
        "retries": 10
      },
      "networks": [
        "app-network"
      ],
      "volumes": {
        "/var/lib/postgresql/data": "auth_db_storage"
      },
      "ports": {
        "5432": "25432"
      }
    },
    "auth_server": {
      "image": "docker.cloudsmith.io/buildone/repository/buildone-auth-server:24.3.0-VG.103",
      "restart": "unless-stopped",
      "environment": {
        "PORT": "3000",
        "APP_URL": "#globals.appUrl",
        "AUTH_DATABASE_URL": "${AUTH_DATABASE_URL:-postgres://${AUTH_DATABASE_CREDENTIALS:-${DEFAULT_DATABASE_CREDENTIALS}}@auth_db_server:5432/auth_db?sslmode=disable}",
        "BETTER_AUTH_SECRET": "${BETTER_AUTH_SECRET}",
        "B1_AUTOMATION_HUB_USER": "${B1_AUTOMATION_HUB_USER:-automation_hub}",
        "B1_AUTOMATION_HUB_EMAIL": "${B1_AUTOMATION_HUB_EMAIL:-automation_hub@build.one}",
        "B1_AUTOMATION_HUB_PASSWORD": "${B1_AUTOMATION_HUB_PASSWORD}",
        "AH_CREDENTIALS": "${AH_CREDENTIALS:-}",
        "AUTHENTICATION_TRUSTED_ORIGINS": "#globals.authenticationTrustedOrigins",
        "MICROSOFT_CLIENT_ID": "${MICROSOFT_CLIENT_ID:-}",
        "MICROSOFT_CLIENT_SECRET": "${MICROSOFT_CLIENT_SECRET:-}",
        "MICROSOFT_TENANT_ID": "${MICROSOFT_TENANT_ID:-}",
        "MICROSOFT_SCOPE": "${MICROSOFT_SCOPE:-}",
        "GOOGLE_CLIENT_ID": "${GOOGLE_CLIENT_ID:-}",
        "GOOGLE_CLIENT_SECRET": "${GOOGLE_CLIENT_SECRET:-}",
        "GITHUB_CLIENT_ID": "${GITHUB_CLIENT_ID:-}",
        "GITHUB_CLIENT_SECRET": "${GITHUB_CLIENT_SECRET:-}",
        "DEPLOYMENT_TYPE": "local",
        "NODE_ENV": "production"
      },
      "networks": [
        "app-network"
      ],
      "depends_on": {
        "auth_db_server": {
          "condition": "service_healthy"
        }
      }
    },
    "web-app": {
      "image": "nomad123/codespaces-nestjs-development:slim",
      "restart": "unless-stopped",
      "environment": {
        "HOST": "0.0.0.0",
        "PORT": "3000",
        "NODE_ENV": "development",
        "APP_URL": "#globals.appUrl"
      },
      "networks": [
        "app-network"
      ],
      "working_dir": "/workspace/src/web-app",
      "command": "npm run dev",
      "volumes": {
        "/workspace": "${WORKSPACE_ROOT}"
      }
    },
    "pg-admin": {
      "image": "dpage/pgadmin4:9",
      "restart": "unless-stopped",
      "environment": {
        "PGADMIN_CONFIG_X_FRAME_OPTIONS": "\"\"",
        "PGADMIN_CONFIG_ALLOW_FRAMING": "True",
        "PGADMIN_CONFIG_PROXY_X_HOST_COUNT": "1",
        "PGADMIN_CONFIG_PROXY_X_FOR_COUNT": "1",
        "PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION": "False",
        "PGADMIN_CONFIG_CSRF_TRUSTED_ORIGINS": "['https://*.github.dev']",
        "PGADMIN_DEFAULT_EMAIL": "${B1_AUTOMATION_HUB_EMAIL:-automation_hub@build.one}",
        "PGADMIN_DEFAULT_PASSWORD": "${B1_AUTOMATION_HUB_PASSWORD}",
        "PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED": "False",
        "PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD": "False",
        "PGADMIN_CONFIG_SERVER_MODE": "False",
        "PGADMIN_CONFIG_CONSOLE_LOG_LEVEL": "10"
      },
      "ports": {
        "80": "2021"
      },
      "networks": [
        "app-network"
      ],
      "volumes": {
        "/pgadmin4/servers.json": "${BUILDONE_CLI_WORKSPACE}/pgadmin.servers.json"
      }
    },
    "web-docs": {
      "image": "docker.cloudsmith.io/buildone/repository/buildone-web-docs:24.3.0-VG.103",
      "restart": "unless-stopped",
      "ports": {
        "80": "5173"
      }
    }
  }
}

=== build-one-labs/starter/.deploy/portainer.deployment.config.json
{
  "$schema": "deployment.config.schema.json",
  "globals": {
    "appUrl": "${APP_URL:-${STACK}.${DOMAIN:-demo.build.one}}",
    "authenticationOIDCRoleId": "${AUTHENTICATION_OIDC_ROLE_ID:-}",
    "authenticationTrustedOrigins": "https://${APP_URL:-${STACK}.${DOMAIN:-demo.build.one}}",
    "authenticationURI": "http://swat_app_server_ts:3000",
    "automationHubImage": "docker.cloudsmith.io/buildone/repository/automation-hub-1-114-3:1.9.4",
    "postgresDbImage": "docker.cloudsmith.io/buildone/repository/build-one-postgres-db:17-2",
    "caddyImage": "docker.cloudsmith.io/buildone/repository/buildone-caddy:${BUILDONE_VERSION}",
    "appServerTsImage": "docker.cloudsmith.io/buildone/repository/buildone-app-server-ts:${BUILDONE_VERSION}",
    "webAppImage": "docker.cloudsmith.io/buildone/repository/buildone-web-app:${BUILDONE_VERSION}",
    "dataImage": "docker.cloudsmith.io/buildone/repository/buildone-data:${BUILDONE_VERSION}"
  },
  "volumes": [
    "ah_db_storage",
    "app_db_storage",
    "b1_db_storage",
    "app-data",
    "db-data",
    "n8n-data",
    "pasoe_logs",
    "redis_storage"
  ],
  "networks": {
    "app-network": {
      "driver": "bridge",
      "driver_opts": {
        "com.docker.network.driver.mtu": 1430
      }
    },
    "traefik": {
      "external": true
    }
  },
  "services": {
    "caddy": {
      "image": "#globals.caddyImage",
      "restart": "unless-stopped",
      "networks": [
        "app-network",
        "traefik"
      ],
      "command": [
        "caddy",
        "run",
        "--config",
        "/etc/caddy/Caddyfile",
        "--adapter",
        "caddyfile"
      ],
      "labels": {
        "traefik.enable": "true",
        "traefik.docker.network": "traefik",
        "traefik.http.routers.${STACK}-buildone-app.rule": "Host(`${STACK}.${DOMAIN:-demo.build.one}`)",
        "traefik.http.routers.${STACK}-buildone-app.entrypoints": "${ENTRYPOINTS:-websecure}",
        "traefik.http.routers.${STACK}-buildone-app.tls.certresolver": "myresolver",
        "traefik.http.services.${STACK}-buildone-app.loadbalancer.server.port": "8080"
      }
    },
    "b1_db_server": {
      "image": "#globals.postgresDbImage",
      "restart": "unless-stopped",
      "environment": {
        "RESET_DATABASES": "${RESET_DATABASES:-FALSE}"
      },
      "healthcheck": {
        "test": [
          "CMD-SHELL",
          "/wait_for_db.sh"
        ],
        "interval": "5s",
        "timeout": "5s",
        "retries": 10
      },
      "networks": [
        "app-network"
      ],
      "volumes": {
        "/var/lib/postgresql/data": "b1_db_storage"
      }
    },
    "swat_app_server_ts": {
      "image": "docker.cloudsmith.io/buildone/repository/buildone-swat-app-server-ts:25.17.0-PVG.20",
      "restart": "unless-stopped",
      "environment": {
        "INIT_CREDENTIALS": "${CREDENTIALS:-}",
        "IMPORT_DATA": "true",
        "PORT": "3000",
        "UPLOAD_DIR": "/app-data/uploads",
        "B1_DATA_FOLDER": "/data/b1",
        "APP_DATA_FOLDER": "/data/app",
        "B1_DATABASE_URL": "${B1_DATABASE_URL:-postgres://${B1_DATABASE_CREDENTIALS:-}@b1_db_server:5432/b1?sslmode=disable}",
        "BETTER_AUTH_SECRET": "${BETTER_AUTH_SECRET}",
        "BETTER_AUTH_URL": "${BETTER_AUTH_URL}",
        "B1_AUTOMATION_HUB_USER": "${B1_AUTOMATION_HUB_USER}",
        "B1_AUTOMATION_HUB_EMAIL": "${B1_AUTOMATION_HUB_EMAIL}",
        "B1_AUTOMATION_HUB_PASSWORD": "${B1_AUTOMATION_HUB_PASSWORD}",
        "AUTHENTICATION_URI": "#globals.authenticationURI",
        "AUTHENTICATION_TRUSTED_ORIGINS": "#globals.authenticationTrustedOrigins",
        "REPOSITORY_SERVICE_TYPE": "POSTGRES",
        "LEGACY_APPLICATION_APPURL": "#globals.appUrl",
        "LEGACY_AUTHENTICATION_ALLOWEDAUTHENTICATION": "${ALLOWED_AUTHENTICATION:-AkiomaUser}",
        "LEGACY_AUTHENTICATION_SSOAUTHENTICATIONURI": "#globals.authenticationURI",
        "LEGACY_AUTHENTICATION_AUTHENTICATIONOIDCROLEID": "#globals.authenticationOIDCRoleId",
        "LEGACY_ENVIRONMENT_URL": "#globals.appUrl",
        "LEGACY_INTEGRATION_GOOGLEAPIKEY": "${GOOGLEAPIKEY:-}",
        "LEGACY_INTEGRATION_KENDOLICENSEKEY": "${KENDO_LICENSE_KEY:-}"
      },
      "networks": [
        "app-network"
      ],
      "depends_on": {
        "b1_db_server": {
          "condition": "service_healthy"
        }
      },
      "volumes": {
        "/app-data": "app-data"
      }
    },
    "app_db_server": {
      "image": "#globals.postgresDbImage",
      "restart": "unless-stopped",
      "environment": {
        "POSTGRES_DB": "app_db",
        "RESET_DATABASES": "${RESET_DATABASES:-FALSE}"
      },
      "healthcheck": {
        "test": [
          "CMD-SHELL",
          "/wait_for_db.sh"
        ],
        "interval": "5s",
        "timeout": "5s",
        "retries": 10
      },
      "networks": [
        "app-network"
      ],
      "volumes": {
        "/var/lib/postgresql/data": "app_db_storage"
      }
    },
    "app_server_ts": {
      "image": "#globals.appServerTsImage",
      "restart": "unless-stopped",
      "environment": {
        "PORT": "3000",
        "APP_DATABASE_URL": "${APP_DATABASE_URL:-postgres://${APP_DATABASE_CREDENTIALS:-}@app_db_server:5432/app_db?sslmode=disable}",
        "BETTER_AUTH_SECRET": "${BETTER_AUTH_SECRET}",
        "BETTER_AUTH_URL": "${BETTER_AUTH_URL}",
        "AUTHENTICATION_URI": "#globals.authenticationURI",
        "NODE_ENV": "prod"
      },
      "networks": [
        "app-network"
      ],
      "depends_on": {
        "app_db_server": {
          "condition": "service_healthy"
        }
      }
    },
    "n8n_db_server": {
      "image": "docker.cloudsmith.io/buildone/repository/automation-hub-db:16-1",
      "restart": "unless-stopped",
      "healthcheck": {
        "test": [
          "CMD-SHELL",
          "/wait_for_db.sh"
        ],
        "interval": "5s",
        "timeout": "5s",
        "retries": 10
      },
      "networks": [
        "app-network"
      ],
      "volumes": {
        "/var/lib/postgresql/data": "ah_db_storage"
      }
    },
    "n8n_init": {
      "image": "#globals.automationHubImage",
      "restart": "no",
      "environment": {
        "DB_POSTGRESDB_HOST": "n8n_db_server",
        "WEBHOOK_URL": "https://${STACK}.${DOMAIN:-demo.build.one}/service/automation"
      },
      "entrypoint": [
        "/db_init.sh"
      ],
      "networks": [
        "app-network"
      ],
      "depends_on": {
        "n8n_db_server": {
          "condition": "service_healthy"
        }
      }
    },
    "n8n": {
      "image": "#globals.automationHubImage",
      "restart": "unless-stopped",
      "environment": {
        "DB_POSTGRESDB_HOST": "n8n_db_server",
        "AUTHENTICATION_OIDC_ROLE_ID": "#globals.authenticationOIDCRoleId",
        "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS": "false",
        "N8N_SECURE_COOKIE": "false",
        "AUTHENTICATION_URI": "${AUTHENTICATION_URI:-}",
        "WEBHOOK_URL": "https://${STACK}.${DOMAIN:-demo.build.one}/service/automation",
        "EXECUTIONS_MODE": "queue",
        "QUEUE_BULL_REDIS_HOST": "redis",
        "QUEUE_HEALTH_CHECK_ACTIVE": "true",
        "B1_N8N_ENV": "prod"
      },
      "networks": [
        "app-network"
      ],
      "depends_on": {
        "n8n_init": {
          "condition": "service_completed_successfully"
        },
        "n8n_init_data": {
          "condition": "service_completed_successfully"
        }
      },
      "volumes": {
        "/workspace/data/": "app-data",
        "/workspace/app/data": "n8n-data"
      }
    },
    "web-app": {
      "image": "#globals.webAppImage",
      "environment": {
        "HOST": "0.0.0.0",
        "PORT": "3000",
        "NODE_ENV": "production",
        "APP_URL": "#globals.appUrl"
      },
      "networks": [
        "app-network"
      ],
      "command": [
        "node",
        "dist/server/index.mjs"
      ]
    },
    "n8n_init_data": {
      "image": "#globals.dataImage",
      "restart": "no",
      "entrypoint": [
        "/workspace/src/data/.build/initialize_automation_hub_data.sh"
      ],
      "volumes": {
        "/update": "n8n-data"
      },
      "networks": [
        "app-network"
      ]
    },
    "redis": {
      "image": "redis:6-alpine",
      "restart": "unless-stopped",
      "healthcheck": {
        "test": [
          "CMD",
          "redis-cli",
          "ping"
        ],
        "interval": "5s",
        "timeout": "5s",
        "retries": 10
      },
      "networks": [
        "app-network"
      ],
      "volumes": {
        "/data": "redis_storage"
      }
    },
    "ah_worker": {
      "image": "#globals.automationHubImage",
      "scale": "${AH_NUM_WORKERS:-1}",
      "entrypoint": [
        "n8n",
        "worker"
      ],
      "depends_on": [
        "n8n"
      ],
      "environment": {
        "EXECUTIONS_MODE": "queue",
        "QUEUE_BULL_REDIS_HOST": "redis",
        "QUEUE_HEALTH_CHECK_ACTIVE": "true"
      },
      "restart": "unless-stopped",
      "networks": [
        "app-network"
      ],
      "volumes": {
        "/workspace/data/": "app-data"
      }
    }
  }
}
